### ISSUE TITLE
Calibration missing for human demonstrations (data tried cfg3)

### ISSUE THREAD

**Issue by zubair-irshad** [rh20t/rh20t_api#10]
Great work! When trying to run the visualize.py script using the `--preprocess` flag with human demonstration data, I get the following:

> FileNotFoundError: [Errno 2] No such file or directory:` 'rh20t/RH20T_cfg3/calib/1640674052372/intrinsics.npy'`

It seems to run fine for robot collected data. I indeed see in `calib` folder there is no corresponding folder named `1640674052372`. I have also tried it for various human generated data in cfg3 downloaded data and it doesn't seem to find any of those in the `calib` folder since they don't exist in the data I downloaded and extracted. Can you please share these folders or provide some insights on how can I access them? Thanks!

**Comment by Vladimirovich2019** [comment]
Hi! I think some of the folders including `1640674052372` are somehow lost, or incorrectly included in `timestamps.npy` file. You may try using an earlier calibration folder by removing `1640674052372` (and all others that do not exist in the `calib` folder) from the list in `rh20t/RH20T_cfg3/calib/timestamps.npy`. We will check on this in the provided dataset files.
