### ISSUE TITLE
Joint info does not match with the robot DOF

### ISSUE THREAD

**Issue by motor-x** [rh20t/rh20t_api#12]
Hi,

I noticed that the robot you were using had either 6 or 7 DOF. However, when loading the joint.npy file for cfg1 and cfg5, the dim of each vector is 14. Could you please let me know why it is not 7?

Best regards,
Yuchen

**Comment by motor-x** [comment]
Also, for cfg6 and cfg7, the dim is 21. Are these three step actions?

**Comment by Vladimirovich2019** [comment]
Hi, Yuchen. Thank you for your attention. Each vector corresponds to a single step of action. We have provided the interval to fetch the joint angles for each robot in [`configs/configs.json`](https://github.com/rh20t/rh20t_api/blob/main/configs/configs.json#L10C10-L10C27), stored with the key `"robot_joint_field"`. For example, for cfg1, simply index the vector with [0, 7]. To use them properly, you may refer to the [updating function](https://github.com/rh20t/rh20t_api/blob/main/utils/robot.py#L35) called from [this line of our visualization script](https://github.com/rh20t/rh20t_api/blob/aa3124434729ed622109a29b2cbb9f3bbb1c5eeb/visualize.py#L367), which loads `joint.npy` with [`get_joint_angles_aligned()`](https://github.com/rh20t/rh20t_api/blob/aa3124434729ed622109a29b2cbb9f3bbb1c5eeb/rh20t_api/scene.py#L594).

**Comment by motor-x** [comment]
Thank you for the quick reply! If I understand correctly, for example, in cfg7, the joint.npy has vector with dim 21, I can just use the range based on the "[robot_joint_field](https://github.com/rh20t/rh20t_api/blob/aa3124434729ed622109a29b2cbb9f3bbb1c5eeb/configs/configs.json#L148C1-L148C37)", right?

**Comment by Vladimirovich2019** [comment]
Yes, you can just use `[0:7]` as the corresponding `"robot_joint_field"` is `[0, 7]`.
