### ISSUE TITLE
Missing 'finish_time' in metadata

### ISSUE THREAD

**Issue by Tavish9** [rh20t/rh20t_api#13]
Hi, thanks for releasing the dataset!

When processing the dataset using `rh20t_dataset_builder`, I encountered a `KeyError: 'finish_time'` problem while handling `RH20T_cfg7/task_0001_user_0014_scene_0002_cfg_0007` at the following code snippet:

```python
with open(os.path.join(base_path, 'metadata.json'), 'r') as f:
    meta = json.load(f)
finish_timestamp = meta['finish_time']
```

It seems like the key 'finish_time' is missing from the metadata. Could you please clarify if this is an issue with the dataset or if this particular trajectory needs to be skipped? I didn’t notice any handling for missing keys in the dataset builder.

Thank you for your assistance!

**Comment by rh20t** [comment]
Hi, I think it's the trajectory needs to be skipped, you can add handling
to that, thanks.

**Comment by Tavish9** [comment]
Thanks for help.
