### ISSUE TITLE
Data missing when extracting cfg3 mp4 data as image

### ISSUE THREAD

**Issue by hipforth** [rh20t/rh20t_api#14]
![image](https://github.com/user-attachments/assets/a499b674-cd6d-49a9-b285-a96f4799a4dd)

task_0041_user_0010_scene_0004_cfg_0003_human/cam_036422060909
and task_0041_user_0010_scene_0004_cfg_0003_human/cam_104422070011
missing color.mp4, also has more missing data

**Comment by Galaxies99** [comment]
Hi,

Cameras sometimes did not record data during data collection due to hardware issues. Just ignore these camera folders where `color.mp4` does not exist.
