### ISSUE TITLE
Download dataset from Google Drive

### ISSUE THREAD

**Issue by lzylucy** [rh20t/rh20t_api#4]
Hello!

Thanks the authors for taking the effort to collect such a large scale dataset. I'm wondering what are some recommended ways to download the dataset from Google Drive using command line. I tried gdown, which worked for once and then constantly gave the following error:
```
Access denied with the following error:

        Too many users have viewed or downloaded this file recently. Please
        try accessing the file again later. If the file you are trying to
        access is particularly large or is shared with many people, it may
        take up to 24 hours to be able to view or download the file. If you
        still can't access a file after 24 hours, contact your domain
        administrator.
```
I also tried using wget directly, which gave the following error:
```
Resolving docs.google.com (docs.google.com)... 142.250.80.110
Connecting to docs.google.com (docs.google.com)|142.250.80.110|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-04-18-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/d81dtkiq1cbbm50scf92l1f91qurhsf6/1693677675000/05821709262819476373/*/1dCRwmdn3cg2330zhY0lIPvG6Q9YGoCYz?e=download&uuid=4432071c-fd90-430a-889f-accff90699d7 [following]
Warning: wildcards not supported in HTTP.
--2023-09-02 14:02:12--  https://doc-04-18-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/d81dtkiq1cbbm50scf92l1f91qurhsf6/1693677675000/05821709262819476373/*/1dCRwmdn3cg2330zhY0lIPvG6Q9YGoCYz?e=download&uuid=4432071c-fd90-430a-889f-accff90699d7
Resolving doc-04-18-docs.googleusercontent.com (doc-04-18-docs.googleusercontent.com)... 142.250.65.225
Connecting to doc-04-18-docs.googleusercontent.com (doc-04-18-docs.googleusercontent.com)|142.250.65.225|:443... connected.
HTTP request sent, awaiting response... 429 Too Many Requests
2023-09-02 14:02:12 ERROR 429: Too Many Requests.
```
Any help would be appreciated!

**Comment by Fang-Haoshu** [comment]
Hi Lucia! I think the problem is that google drive would block the download if too many users have viewed or downloaded this file recently. I have tried to figure out ways to bypass this issue but have no luck. I think the current solution is to wait and check again several hours later. Does all the cfg give the same error? And BTW, is it possible to download it from Baidu Pan in the US?

**Comment by lzylucy** [comment]
Hi Haoshu, thanks for the reply! I tried a few other cfg and it gave the same error with Google Drive. I think downloading from Baidu Pan is possible, will try it!

**Comment by lzylucy** [comment]
Update: I tried downloading from google drive using [Rclone](https://rclone.org/) and it works now! Closing this issue.

**Comment by Shaowang123** [comment]
Hello!

Thank you to the author for the effort in collecting such a large-scale dataset. I would like to know where I can obtain some video samples of the "Human Demonstration, Robot Manipulation" section. I would like to see what the operation videos look like.

**Comment by pongnguy** [comment]
I get quota exceeded for google drive.  you could try hosting on aws bucket and allow users to download using their own account to avoid the egrees fees
