### ISSUE TITLE
Question about the extrinsic of the in-hand camera

### ISSUE THREAD

**Issue by Oliverbansk** [rh20t/rh20t_api#7]
Hi! This is really fantastic work! The APIs are so clearly set and convenient to use!

I have been exploring your dataset and I have a question about the extrinsic of the in-hand camera. The in-hand camera is actually moving with the end-effector, so is it okay to say that its extrinsic is also changing with the timestamp? 

I'm wondering if you can provide more related information about the changing extrinsic of the moving in-hand camera, since the `RH20TScene.extrinsics_base_aligned` field only contains one single extrinsic for each camera.

Can I compute it via forward-kinematics? (Use the end-effector frame's SE3 transformation (related to the base) to compute the in-hand camera extrinsic.)

Thank you so much!

**Comment by Fang-Haoshu** [comment]
Hi! You are right. TO obtain the inhand camera extrinsic to the base, you can obtain the relative T between the camera and the tcp in the first frame, and for the following frames, you can obtain the inhand extrinsic by the relative T and the tcp pose. We provided the tcp pose of the gripper in the base coordinate, which is in the file 'transformed/tcp_base.npy'

**Comment by Oliverbansk** [comment]
Got it! Thank you!!

**Comment by Davidyao99** [comment]
@Fang-Haoshu Hi, I am trying to obtain the extrinsics matrix for the RGB camera on the gripper. Could you provide a little bit more detail on how to attain this matrix? I am a little confused with what information is in tcp_base.npy and tcp.npy, and any  clarifications will be tremendously helpful!

**Comment by Vladimirovich2019** [comment]
@Davidyao99 Hi! We manually measured the transformation matrix from `tcp` to the RGB camera on the gripper, named `"tc_mat"` and stored in the configuration [file](https://github.com/rh20t/rh20t_api/blob/main/configs/configs.json). The difference between `tcp_base.npy` and `tcp.npy` is that the former uses the robot arm's root as reference, while the latter uses a randomly placed calibration marker as reference. We used `"tc_mat"` to preprocess `tcp.npy` into `tcp_base.npy` [here](https://github.com/rh20t/rh20t_api/blob/main/rh20t_api/scene.py#L276). You may refer to the code and obtain the required matrix by doing something like `tc_mat @ tcp_base`.

**Comment by Davidyao99** [comment]
@Vladimirovich2019 I see, thank you so much for the response, I understand now! I faced another issue when trying to understand this dataset. I notice that during the extraction code [here](https://github.com/rh20t/rh20t_api/blob/aa3124434729ed622109a29b2cbb9f3bbb1c5eeb/rh20t_api/extract.py#L27), each frame from the video is mapped to timestamps.npy. However, looking over the timestamps, I noticed that the time intervals are not consistent. It seems like the RGB frames obtained did not originate from a constant FPS? Additionally, I notice that for some cameras, the intervals actually differ quite a lot, with maximum interval of 600ms and minimum interval of 92ms. Do you have any insights as to what is happening here?

**Comment by Vladimirovich2019** [comment]
@Davidyao99 We collected frames at a constant target FPS, but due to the computer's limited processing capacity (it handles data streams from ~8 cameras and multiple other sensors), the actual frame intervals might vary. My collaborators could provide more details if needed.

**Comment by Davidyao99** [comment]
I see I see, just wondering why can't the readings be collected by the sensors independently themselves, before being collated by the computer. So each sensor reading will have its own independent timestamps, and during downstream tasks that require multi-sensor inputs, the readings from the closest timestamps for each sensor can be used. Or perhaps it is actually that crucial to make sure all the sensors capture at the same time (and sacrifice the constant FPS)? 

Just curious as I am not familiar with this kind of data preparation processes!

**Comment by misrolox** [comment]
> [@Davidyao99](https://github.com/Davidyao99) Hi! We manually measured the transformation matrix from `tcp` to the RGB camera on the gripper, named `"tc_mat"` and stored in the configuration [file](https://github.com/rh20t/rh20t_api/blob/main/configs/configs.json). The difference between `tcp_base.npy` and `tcp.npy` is that the former uses the robot arm's root as reference, while the latter uses a randomly placed calibration marker as reference. We used `"tc_mat"` to preprocess `tcp.npy` into `tcp_base.npy` [here](https://github.com/rh20t/rh20t_api/blob/main/rh20t_api/scene.py#L276). You may refer to the code and obtain the required matrix by doing something like `tc_mat @ tcp_base`.

I see in configurations 5, 6, and 7, there are 2 in_hand_serials, so I assume 2 cameras attached to the gripper? But there is only one tc_mat. How would one calculate the extrinsics there?
