### ISSUE TITLE
URDF of the robot hands

### ISSUE THREAD

**Issue by bearpaw** [rh20t/rh20t_api#8]
Thanks for providing the dataset.

I checked the repo and found the URDFs only contain the robot arms. Is it possible to also share the URDF of the robot hand (and the gripper if you're using customized fingers)? Thanks!

**Comment by Fang-Haoshu** [comment]
Hi Wei! Sorry but we don't have the URDFs for the gripper actually. We used Robotiq, Dahuan and AG-95, and maybe they can be found on the internet. The extended fingertip is around 6cm. The Franka subset might contain the hand model.
Best,
HS

**Comment by bearpaw** [comment]
Thanks!
